const express = require('express');
const router = express.Router();
const pool = require('../config/database');

/**
 * POST /api/registrations
 * Submit new registration (public endpoint)
 */
router.post('/', async (req, res) => {
  try {
    const {
      fullName,
      companyName,
      whatsappNumber,
      email,
      foodRestriction,
      allergies,
      confirmationAttendance,
      numberOfPeople
    } = req.body;

    // Validation
    if (!fullName || !email || !companyName) {
      return res.status(400).json({
        success: false,
        error: 'Full name, email, and company name are required',
        details: {
          fullName: !fullName ? 'Full name is required' : null,
          email: !email ? 'Email is required' : null,
          companyName: !companyName ? 'Company name is required' : null
        }
      });
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid email format'
      });
    }

    // Check for duplicate email
    const existingReg = await pool.query(
      'SELECT id FROM registrations WHERE email = $1',
      [email]
    );

    if (existingReg.rows.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Email already registered'
      });
    }

    // Insert registration (UUID will be auto-generated by database)
    const result = await pool.query(
      `INSERT INTO registrations 
       (full_name, company_name, whatsapp_number, email, 
        food_restriction, allergies, confirmation_attendance, number_of_people,
        ip_address, user_agent) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
       RETURNING id, full_name, created_at`,
      [
        fullName,
        companyName,
        whatsappNumber || '',
        email,
        foodRestriction || '',
        allergies || '',
        confirmationAttendance || '',
        numberOfPeople || 1,
        req.ip,
        req.get('user-agent')
      ]
    );

    // Log the result for debugging
    console.log('Registration inserted successfully');
    console.log('Result rows:', result.rows);
    console.log('ID from database:', result.rows[0]?.id);
    console.log('ID type:', typeof result.rows[0]?.id);
    console.log('ID value:', JSON.stringify(result.rows[0]?.id));

    const registrationId = result.rows[0]?.id;
    
    // Ensure ID is converted to string if it's not already
    const idString = registrationId ? String(registrationId) : null;
    
    if (!idString) {
      console.error('ERROR: Registration ID is null or undefined!');
      console.error('Full result:', JSON.stringify(result.rows[0], null, 2));
    }

    const responseData = {
      success: true,
      message: 'Registration submitted successfully',
      data: {
        id: idString,
        fullName: result.rows[0].full_name,
        createdAt: result.rows[0].created_at
      }
    };

    console.log('Sending response:', JSON.stringify(responseData, null, 2));
    console.log('Response ID:', responseData.data.id);
    console.log('Response ID type:', typeof responseData.data.id);

    res.status(201).json(responseData);
  } catch (error) {
    console.error('Registration error:', error);
    console.error('Error stack:', error.stack);
    console.error('Error message:', error.message);
    console.error('Error details:', JSON.stringify(error, Object.getOwnPropertyNames(error)));
    
    res.status(500).json({
      success: false,
      error: 'Failed to submit registration',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

/**
 * GET /api/registrations/:id
 * Get registration detail by ID (public endpoint)
 */
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;

    const result = await pool.query(
      'SELECT * FROM registrations WHERE id = $1',
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Registration not found'
      });
    }

    const reg = result.rows[0];
    
    res.json({
      success: true,
      data: {
        id: reg.id,
        fullName: reg.full_name,
        companyName: reg.company_name,
        whatsappNumber: reg.whatsapp_number,
        email: reg.email,
        foodRestriction: reg.food_restriction,
        allergies: reg.allergies,
        confirmationAttendance: reg.confirmation_attendance,
        numberOfPeople: reg.number_of_people,
        createdAt: reg.created_at
      }
    });
  } catch (error) {
    console.error('Fetch registration error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch registration'
    });
  }
});

/**
 * GET /api/registrations/:id
 * Public read-only registration detail (for QR scans)
 */
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      `SELECT id, full_name, company_name, whatsapp_number, email,
              food_restriction, allergies, confirmation_attendance,
              number_of_people, created_at
       FROM registrations
       WHERE id = $1`,
      [id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'Registration not found'
      });
    }

    res.json({
      success: true,
      data: result.rows[0]
    });
  } catch (error) {
    console.error('Get registration error:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch registration'
    });
  }
});

module.exports = router;
